export const skillsList: string[] = [
  "HTML5",
  "CSS3",
  "CSS-modules",
  "SASS",
  "SCSS",
  "FlexBox",
  "Grid",
  "Адаптивная верстка",
  "JavaScript",
  "TypeScript",
  "React",
  "Styled-components",
  "Emotion",
  "Material UI",
  "Redux Toolkit",
  "Node.js",
  "Nest.js",
  "Phaser.js",
  "Axios",
  "Jest",
  "React testing library",
  "Git",
  "Webpack",
  "VS Code",
  "Bitbucket",
  "Jenkins",
  "Figma",
  "Наставничество",
  "Code review",
  "Работа с AI"
];
