export const skillsList: string[] = [
  "HTML",
  "CSS",
  "SASS",
  "SCSS",
  "FlexBox",
  "Grid",
  "Bootstrap",
  "JavaScript",
  "TypeScript",
  "Git",
  "React",
  "Styled-components",
  "Redux Toolkit",
  "Material UI",
  "Nest.js",
  "Axios",
  "Адаптивная верстка",
  "БЭМ",
  "VS Code",
  "Bitbucket",
  "Figma",
  "Adobe Photoshop",
  "iSpring Suite"
];
